FROM rust:1.86-alpine

# Fix linker (crt*.o files are in Rust sysroot)
RUN ln -sf /usr/local/rustup/toolchains/1.86.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained/crti.o /usr/lib/gcc/x86_64-alpine-linux-musl/14.2.0/ && \
    ln -sf /usr/local/rustup/toolchains/1.86.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained/crtn.o /usr/lib/gcc/x86_64-alpine-linux-musl/14.2.0/ && \
    ln -sf /usr/local/rustup/toolchains/1.86.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained/crt1.o /usr/lib/gcc/x86_64-alpine-linux-musl/14.2.0/

WORKDIR /app
COPY Cargo.toml .
COPY src/ src/

RUN cargo build --release && cp target/release/rotate-proxy /usr/local/bin/ && strip /usr/local/bin/rotate-proxy

# Minimal runtime
FROM alpine:3.21
COPY --from=0 /usr/local/bin/rotate-proxy /usr/local/bin/rotate-proxy
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
EXPOSE 8080 8081
ENV LISTEN_ADDR=0.0.0.0:8080
ENV TUNNEL_MAX_LIFETIME_SECS=120
ENTRYPOINT ["/entrypoint.sh"]
